"""Project cards and the draft project catalog (spec §23-§42).

The catalog (names, costs, effects, VP) is balance data and expected to change
during playtesting. Effects are a small closed set interpreted by the engine.

Costs are sized for the 5-unit economy (2/1/1/1 production, upkeep 3), where a
city has roughly 2 spare units per round — smaller than the spec's original
suggestions (§39-§41), which assumed 10-unit production:

- City: 3 units, 2 types (concentrated: rewards specialisation); Small storage 2 units
- Grand City: base + 2 units in 2 new types, 1 VP
- Market: 3 units, 2-3 types
- Prestige small 3 units / 2-3 types; medium 4-5 / 4-5; major 6-8 / 6-8.
  Diversity, not volume, is what makes the big ones hard.

The hand-written cards below define each card's *shape* (units per resource
type), effect and VP. Which resources fill those shapes is generated by
``build_catalog`` so that demand is spread evenly — optionally tilted so basic
goods dominate early cards and refined goods dominate late ones (see
``RESOURCE_SPLITS``). Names may no longer match their ingredients; balance wins.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, replace
from enum import Enum
from functools import lru_cache

from .config import DEFAULT_CONFIG
from .economy import RESOURCES, Resource

G, L, T, I, C, O, W, S = RESOURCES


class ProjectCategory(str, Enum):
    CITY = "city"
    MARKET = "market"
    PRESTIGE = "prestige"


class MarketAxis(str, Enum):
    SUPPLY = "supply"
    DEMAND = "demand"


class MarketLevel(str, Enum):
    DOWN = "down"
    NEUTRAL = "neutral"
    UP = "up"


class EffectKind(str, Enum):
    NONE = "none"
    PRODUCTION = "production"  # +amount production of resource
    INCOME = "income"  # +amount cash at Round Start
    UPKEEP_REDUCTION = "upkeep_reduction"  # -amount upkeep of resource
    STORAGE = "storage"  # +amount storage capacity
    MARKET = "market"  # sets the global axis/level slot for resource


@dataclass(frozen=True)
class Effect:
    kind: EffectKind = EffectKind.NONE
    resource: Resource | None = None
    amount: int = 0
    axis: MarketAxis | None = None
    level: MarketLevel | None = None

    def describe(self) -> str:
        res = self.resource.value.title() if self.resource else ""
        match self.kind:
            case EffectKind.PRODUCTION:
                return f"+{self.amount} {res} production each round"
            case EffectKind.INCOME:
                return f"+${self.amount} income each round"
            case EffectKind.UPKEEP_REDUCTION:
                return f"-{self.amount} {res} upkeep"
            case EffectKind.STORAGE:
                return f"+{self.amount} storage"
            case EffectKind.MARKET:
                return f"{res} {self.axis.value.title()} {self.level.value.title()} (global)"
        return ""


@dataclass(frozen=True)
class ProjectCard:
    id: str
    name: str
    category: ProjectCategory
    cost: dict[Resource, int]
    effect: Effect = Effect()
    vp: int = 0
    tier: str | None = None  # prestige only: "small" | "medium" | "major"

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "category": self.category.value,
            "cost": {r.value: n for r, n in self.cost.items()},
            "effect": self.effect.describe(),
            "effect_kind": self.effect.kind.value,
            "vp": self.vp,
            "tier": self.tier,
        }


# --- City Projects: concentrated costs, durable personal upgrades (spec §29, §39) ---


def _city(id: str, name: str, cost: dict[Resource, int], effect: Effect) -> ProjectCard:
    return ProjectCard(id=id, name=name, category=ProjectCategory.CITY, cost=cost, effect=effect)


def _prod(r: Resource) -> Effect:
    return Effect(EffectKind.PRODUCTION, resource=r, amount=1)


def _storage(amount: int) -> Effect:
    return Effect(EffectKind.STORAGE, amount=amount)


def _relief(r: Resource) -> Effect:
    return Effect(EffectKind.UPKEEP_REDUCTION, resource=r, amount=1)


_BASE_CITY_PROJECTS: tuple[ProjectCard, ...] = (
    _city("irrigation", "Irrigation Canals", {G: 2, T: 1}, _prod(G)),
    _city("breeding-pens", "Breeding Pens", {L: 2, G: 1}, _prod(L)),
    _city("sawmill", "Sawmill", {T: 2, O: 1}, _prod(T)),
    _city("deep-mine", "Deep Mine", {I: 2, T: 1}, _prod(I)),
    _city("weaving-hall", "Weaving Hall", {C: 2, L: 1}, _prod(C)),
    _city("smithy", "Smithy", {O: 2, I: 1}, _prod(O)),
    _city("terraces", "Vineyard Terraces", {W: 2, T: 1}, _prod(W)),
    _city("spice-gardens", "Spice Gardens", {S: 2, G: 1}, _prod(S)),
    # Storage: +5 each, with Grand versions; cheap "Small" +3 versions are below.
    _city("warehouse", "Warehouse", {T: 2, I: 1}, _storage(5)),
    _city("granary", "Granary", {G: 2, L: 1}, _storage(5)),
    _city("depot", "Depot", {O: 2, I: 1}, _storage(5)),
    _city("counting-house", "Counting House", {C: 2, I: 1}, Effect(EffectKind.INCOME, amount=2)),
    _city("trading-post", "Trading Post", {S: 2, W: 1}, Effect(EffectKind.INCOME, amount=2)),
    _city("fishing-fleet", "Fishing Fleet", {T: 2, C: 1}, _relief(G)),
    _city("hunting-lodge", "Hunting Lodge", {T: 2, I: 1}, _relief(L)),
    _city("stone-quarry", "Stone Quarry", {I: 2, O: 1}, _relief(T)),
    _city("bronze-foundry", "Bronze Foundry", {O: 2, W: 1}, _relief(I)),
    _city("tannery", "Tannery", {L: 2, S: 1}, _relief(C)),
    _city("artisan-guild", "Artisan Guild", {I: 2, C: 1}, _relief(O)),
    _city("brewery", "Brewery", {G: 2, T: 1}, _relief(W)),
    _city("salt-works", "Salt Works", {I: 2, L: 1}, _relief(S)),
)

# Non-prestige projects never award more than this many VP.
MAX_NON_PRESTIGE_VP = 2


def _grand(card: ProjectCard) -> ProjectCard:
    """Same effect, a few more goods in new types, and a little prestige (no cash cost).

    Extra cost: 1 each of two resources the card doesn't use yet — so the VP
    comes from diversity, like Prestige projects.
    """
    main = max(card.cost, key=lambda r: card.cost[r])
    i = RESOURCES.index(main)
    extras = [r for r in (RESOURCES[(i + k) % len(RESOURCES)] for k in range(4, 8)) if r not in card.cost][:2]
    cost = dict(card.cost)
    for r in extras:
        cost[r] = 1
    return ProjectCard(
        id=f"grand-{card.id}",
        name=f"Grand {card.name}",
        category=card.category,
        cost=cost,
        effect=card.effect,
        vp=1,
    )


# Every City project exists as a plain version and a "Grand" version that also scores.
# Small storage: the cheapest cards in the game (2 resources, +3 storage). No Grand versions.
_SMALL_STORAGE: tuple[ProjectCard, ...] = (
    _city("small-warehouse", "Small Warehouse", {T: 1, I: 1}, _storage(3)),
    _city("small-cellar", "Small Cellar", {W: 1, T: 1}, _storage(3)),
    _city("small-granary", "Small Granary", {G: 1, L: 1}, _storage(3)),
    _city("small-barn", "Small Barn", {L: 1, T: 1}, _storage(3)),
    _city("small-depot", "Small Depot", {O: 1, I: 1}, _storage(3)),
)

_HANDWRITTEN_CITY: tuple[ProjectCard, ...] = (
    _BASE_CITY_PROJECTS + _SMALL_STORAGE + tuple(_grand(c) for c in _BASE_CITY_PROJECTS)
)


# --- Market Projects: one card per resource x axis x direction (spec §30-§35, §40) ---

_MARKET_TEMPLATES: tuple[tuple[MarketAxis, MarketLevel, str, tuple[tuple[int, int], ...]], ...] = (
    # (axis, level, name suffix, ((resource offset, units), ...)) — offsets wrap around RESOURCES
    (MarketAxis.SUPPLY, MarketLevel.UP, "Subsidy", ((0, 1), (3, 1), (5, 1))),
    (MarketAxis.SUPPLY, MarketLevel.DOWN, "Embargo", ((2, 1), (4, 1), (6, 1))),
    (MarketAxis.DEMAND, MarketLevel.UP, "Craze", ((1, 2), (6, 1))),
    (MarketAxis.DEMAND, MarketLevel.DOWN, "Substitutes", ((3, 2), (7, 1))),
)


def _market_projects() -> tuple[ProjectCard, ...]:
    cards = []
    for i, resource in enumerate(RESOURCES):
        for axis, level, suffix, parts in _MARKET_TEMPLATES:
            cost = {RESOURCES[(i + off) % len(RESOURCES)]: n for off, n in parts}
            cards.append(
                ProjectCard(
                    id=f"{resource.value}-{axis.value}-{level.value}",
                    name=f"{resource.value.title()} {suffix}",
                    category=ProjectCategory.MARKET,
                    cost=cost,
                    effect=Effect(EffectKind.MARKET, resource=resource, axis=axis, level=level),
                )
            )
    return tuple(cards)


MARKET_PROJECTS: tuple[ProjectCard, ...] = _market_projects()


# --- Prestige Projects: VP, increasingly diverse costs by tier (spec §37, §41-§42) ---


def _prestige(id: str, name: str, tier: str, cost: dict[Resource, int], vp: int) -> ProjectCard:
    return ProjectCard(
        id=id, name=name, category=ProjectCategory.PRESTIGE, cost=cost, vp=vp, tier=tier
    )


_HANDWRITTEN_PRESTIGE: tuple[ProjectCard, ...] = (
    # Small: 3 units; 2 VP for two resource types, 3 VP for three
    _prestige("fountain", "Town Fountain", "small", {I: 1, T: 1, G: 1}, 3),
    _prestige("market-square", "Market Square", "small", {T: 2, G: 1}, 2),
    _prestige("harvest-festival", "Harvest Festival", "small", {G: 1, L: 1, W: 1}, 3),
    _prestige("bell-tower", "Bell Tower", "small", {I: 2, O: 1}, 2),
    _prestige("tapestry", "Grand Tapestry", "small", {C: 1, W: 1, S: 1}, 3),
    _prestige("feast-hall", "Feast Hall", "small", {L: 2, W: 1}, 2),
    _prestige("spice-bazaar", "Spice Bazaar", "small", {S: 1, C: 1, T: 1}, 3),
    _prestige("statue", "Founder's Statue", "small", {I: 1, O: 1, L: 1}, 3),
    # Medium: 4-5 units, 4-5 types; 4 VP for 4 units, 5 VP for 5
    _prestige("library", "Library", "medium", {T: 1, C: 1, W: 1, S: 1}, 4),
    _prestige("guildhall", "Guildhall", "medium", {I: 1, O: 1, C: 1, L: 1}, 4),
    _prestige("racecourse", "Racecourse", "medium", {L: 1, G: 1, T: 1, W: 1}, 4),
    _prestige("theater", "Theater", "medium", {C: 1, W: 1, T: 1, O: 1, G: 1}, 5),
    _prestige("botanical-garden", "Botanical Garden", "medium", {S: 1, G: 1, T: 1, W: 1, L: 1}, 5),
    _prestige("university", "University", "medium", {C: 1, O: 1, S: 1, W: 1, I: 1}, 5),
    _prestige("lighthouse", "Lighthouse", "medium", {T: 2, I: 1, O: 1, S: 1}, 5),
    _prestige("arena", "Arena", "medium", {I: 2, T: 1, L: 1, G: 1}, 5),
    # Major: 6-8 units, 6-8 types; the variety is the challenge
    _prestige("cathedral", "Cathedral", "major", {T: 1, I: 1, C: 1, O: 1, W: 1, S: 1}, 7),
    _prestige("great-harbor", "Great Harbor", "major", {T: 2, I: 1, O: 1, G: 1, L: 1, S: 1}, 8),
    _prestige("colosseum", "Colosseum", "major", {I: 2, T: 1, L: 1, G: 1, O: 1, W: 1}, 8),
    _prestige("imperial-mint", "Imperial Mint", "major", {I: 2, O: 2, S: 1, W: 1, C: 1, G: 1}, 9),
    _prestige(
        "observatory", "Grand Observatory", "major",
        {I: 1, O: 1, C: 1, S: 1, W: 1, G: 1, T: 1}, 8,
    ),
    _prestige(
        "hanging-gardens", "Hanging Gardens", "major",
        {S: 1, G: 1, W: 1, T: 1, C: 1, L: 1, O: 1}, 8,
    ),
    _prestige(
        "royal-palace", "Royal Palace", "major",
        {C: 2, W: 1, S: 1, G: 1, L: 1, I: 1, O: 1}, 9,
    ),
    _prestige(
        "grand-exhibition", "Grand Exhibition", "major",
        {G: 1, L: 1, T: 1, I: 1, C: 1, O: 1, W: 1, S: 1}, 10,
    ),
)


# --- Generated ingredients (balanced demand, optional basic -> refined arc) ---

BASIC: tuple[Resource, ...] = RESOURCES[:4]  # Grain, Livestock, Timber, Iron
REFINED: tuple[Resource, ...] = RESOURCES[4:]  # Cloth, Tools, Wine, Spices

# Share of each card group's units that are basic goods (the rest are refined).
# Within each half, all four resources get an equal share. Market cards are
# always rotationally symmetric (50/50) and not affected.
RESOURCE_SPLITS: dict[str, dict[str, float] | None] = {
    "handwritten": None,  # the original hand-picked ingredients (uneven: Timber/Iron heavy)
    "even": {"city": 0.5, "grand": 0.5, "small": 0.5, "medium": 0.5, "major": 0.5},
    "gentle": {"city": 0.65, "grand": 0.5, "small": 0.65, "medium": 0.5, "major": 0.35},
    "strong": {"city": 0.75, "grand": 0.5, "small": 0.75, "medium": 0.5, "major": 0.2},
}


def _targets(units: int, basic_share: float) -> dict[Resource, float]:
    per_basic = units * basic_share / len(BASIC)
    per_refined = units * (1 - basic_share) / len(REFINED)
    return {r: per_basic if r in BASIC else per_refined for r in RESOURCES}


def _pick(deficit: dict[Resource, float], exclude: set[Resource], card_index: int) -> Resource:
    """Resource with the biggest remaining deficit; ties rotate by card so cards differ."""
    n = len(RESOURCES)
    return max(
        (r for r in RESOURCES if r not in exclude),
        key=lambda r: (round(deficit[r], 6), -((RESOURCES.index(r) - card_index) % n)),
    )


def _fill(cards: tuple[ProjectCard, ...], basic_share: float) -> tuple[ProjectCard, ...]:
    """Re-assign each card's ingredients, keeping its shape, to hit the target split."""
    total = sum(sum(c.cost.values()) for c in cards)
    target = _targets(total, basic_share)
    assigned: Counter[Resource] = Counter()
    result = []
    for i, card in enumerate(cards):
        cost: dict[Resource, int] = {}
        for amount in sorted(card.cost.values(), reverse=True):
            deficit = {r: target[r] - assigned[r] for r in RESOURCES}
            r = _pick(deficit, set(cost), i)
            cost[r] = amount
            assigned[r] += amount
        result.append(replace(card, cost=cost))
    return tuple(result)


def _grand_from(plain: tuple[ProjectCard, ...], basic_share: float) -> tuple[ProjectCard, ...]:
    """Grand variants: the plain cost plus 1 each of two new resources, steered to the split."""
    total = sum(sum(c.cost.values()) + 2 for c in plain)
    target = _targets(total, basic_share)
    assigned: Counter[Resource] = Counter()
    for c in plain:
        assigned.update(c.cost)
    result = []
    for i, card in enumerate(plain):
        cost = dict(card.cost)
        for _ in range(2):
            deficit = {r: target[r] - assigned[r] for r in RESOURCES}
            r = _pick(deficit, set(cost), i)
            cost[r] = 1
            assigned[r] += 1
        result.append(
            ProjectCard(
                id=f"grand-{card.id}",
                name=f"Grand {card.name}",
                category=card.category,
                cost=cost,
                effect=card.effect,
                vp=1,
            )
        )
    return tuple(result)


@lru_cache(maxsize=None)
def build_catalog(split: str) -> tuple[tuple[ProjectCard, ...], tuple[ProjectCard, ...], tuple[ProjectCard, ...]]:
    """(city, market, prestige) cards for a resource split from ``RESOURCE_SPLITS``."""
    if split not in RESOURCE_SPLITS:
        raise ValueError(f"Unknown resource split {split!r}; options: {', '.join(RESOURCE_SPLITS)}")
    shares = RESOURCE_SPLITS[split]
    if shares is None:
        return _HANDWRITTEN_CITY, MARKET_PROJECTS, _HANDWRITTEN_PRESTIGE
    plain = _fill(_BASE_CITY_PROJECTS + _SMALL_STORAGE, shares["city"])
    has_grand = [c for c in plain if not c.id.startswith("small-")]
    city = plain + _grand_from(tuple(has_grand), shares["grand"])
    prestige = tuple(
        card
        for tier in ("small", "medium", "major")
        for card in _fill(tuple(c for c in _HANDWRITTEN_PRESTIGE if c.tier == tier), shares[tier])
    )
    return city, MARKET_PROJECTS, prestige


# Default catalog (matches BalanceConfig.resource_split).
CITY_PROJECTS, _, PRESTIGE_PROJECTS = build_catalog(DEFAULT_CONFIG.resource_split)
